### ISSUE TITLE
Error when uploading shapefile Opportunity Dataset

### ISSUE THREAD

**Issue by marcusyoung** [conveyal/analysis-ui#1083]
**Describe the bug**
Error when uploading shapefile

`null com.conveyal.taui.AnalysisServerException at com.conveyal.taui.AnalysisServerException.fileUpload(AnalysisServerException.java:35) at com.conveyal.taui.controllers.OpportunityDatasetController.createGridsFromShapefile(OpportunityDatasetController.java:363) at com.conveyal.taui.controllers.OpportunityDatasetController.lambda$createOpportunityDataset$5(OpportunityDatasetController.java:234) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) `

**To Reproduce**

1. Go to 'Opportunity Datasets'
2. Browse to shapefile
3. Select unzipped .shp .shx .dbf and .prj
4. Click Upload

**Expected behavior**
The shapefile to be loaded

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser: Firefox
- Version 75.0

**Comment by marcusyoung** [comment]
Think this might be an issue with the shapefile. Closing for now.
