### ISSUE TITLE
Error modal stack trace shows UI code instead of message from backend

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/analysis-ui#1538]
**Describe the bug**
The backend sends an error message with a 400 response (e.g. "Routing server timed out. For the complexity of this scenario, your request may have too many simulated schedules. If you are using Routing Engine version < 4.5.1, your scenario may still be in preparation and you should try again in a few minutes."), but the expandable stack trace in the error modal shows minified UI code:
```
Error: 
Bad Request
    at Pe (https://conveyal.dev/_next/static/chunks/e31d402fc4ec321e46a02517da2eab28f9cff456.a8f031d3000c0dd1dbd6.js:1:50669)
    at ro (https://conveyal.dev/_next/static/chunks/framework.36e5d30ecc6dc4b81c51.js:1:72362)
    at Bo (https://conveyal.dev/_next/static/chunks/framework.36e5d30ecc6dc4b81c51.js:1:81929)
    at Qu (https://conveyal.dev/_next/static/chunks/framework.36e5d30ecc6dc4b81c51.js:1:125811)
    at Pi (https://conveyal.dev/_next/static/chunks/framework.36e5d30ecc6dc4b81c51.js:1:111994)
    at xi (https://conveyal.dev/_next/static/chunks/framework.36e5d30ecc6dc4b81c51.js:1:111922)
    at _i (https://conveyal.dev/_next/static/chunks/framework.36e5d30ecc6dc4b81c51.js:1:111785)
    at vi (https://conveyal.dev/_next/static/chunks/framework.36e5d30ecc6dc4b81c51.js:1:108751)
    at https://conveyal.dev/_next/static/chunks/framework.36e5d30ecc6dc4b81c51.js:1:58130
    at t.unstable_runWithPriority (https://conveyal.dev/_next/static/chunks/framework.36e5d30ecc6dc4b81c51.js:1:3875)
```

**To Reproduce**
1. Disable transit modes, set direct mode to walk
1. Set walk speed to 0 in the JSON
1. Fetch results

Potentially related:
On production, setting walk speed to 0 with direct mode walk, the backend IllegalArgumentException message "Speed of access mode must be greater than 0." shows up in an error modal; but on staging, the message sometimes shows up in the sidebar as a modification error.

**Comment by trevorgerhardt** [comment]
Do the errors get reported differently on a cluster deployment than locally? I'm seeing the correct error reporting locally still using the latest version of r5. 

cc: @abyrd

**Comment by ansoncfit** [comment]
As just discussed, I did not record an important detail -- my originally reported "steps to reproduce" will trigger an `IllegalArgumentException` sent in a `ScenarioApplicationError` that the UI handles well.

If you instead set the direct mode to bike in step 1, the worker will time out and the broker will send back a 400 with a `message` (via `BrokerController.jsonResponse()`). That response is what leads to the originally reported problem.
