### ISSUE TITLE
Route alignment from shapefile has bad createdBy field

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#1614]
Running manual "Advanced Region" test "upload route alignment shapefile", the upload and modification creation seem fine from the modification editor. But when I try to run an analysis it fails.

```
10:21:32.473 [qtp2081529809-31] ERROR c.c.a.c.eventbus.ErrorLogger - User abyrd@conveyal.com of group conveyal accessing /api/analysis: java.lang.RuntimeException: IOException encountered while reading from a byte array input stream
	at org.mongojack.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:67) ...
	at com.conveyal.analysis.persistence.MongoMap.findPermitted(MongoMap.java:82)
	at com.conveyal.analysis.models.AnalysisRequest.createScenario(AnalysisRequest.java:167)
	at com.conveyal.analysis.models.AnalysisRequest.populateTask(AnalysisRequest.java:193)
	at com.conveyal.analysis.controllers.BrokerController.singlePoint(BrokerController.java:142)

Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@ce823f6; pos: 752] (through reference chain: com.conveyal.analysis.models.AddTripPattern["createdBy"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
```

The backend cannot decode the AddTripPattern document from Mongo, because its createdBy field is not a string. It's an object containing a gravatar image url, idToken etc. (some kind of internal Auth0 object?)

The test grid lists this test as fully automated - we should look at the automated test and its results and see if/why it's not detecting the problem with the single-point analysis.

**Comment by trevorgerhardt** [comment]
The code error is easy to track down: https://github.com/conveyal/analysis-ui/blob/f500f5d8fbedb40609945ca276ac241d2c56673e/lib/db/authenticated-collection.ts#L84

should be `this.user.email`.

But the Cypress tests for importing from a Shapefile: https://github.com/conveyal/analysis-ui/blob/dev/cypress/integration/modifications/import-from-shapefile.ts do not run a single point analysis, which should be fairly simple to add at the end of that test.
