### ISSUE TITLE
MapDB corrupted (even on S3?)

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#273]
Vincent in Marseille has created a scenario, working in Chrome. He gets the following error:

![image001](https://cloud.githubusercontent.com/assets/112871/22545281/0431a17a-e973-11e6-804b-4d40a7b7743c.png)

It sounds like between this and #228 he's been unable to do anything with the scenario editor.

**Comment by abyrd** [comment]
Also @mattwigway if you have any idea what's going on here or in #228 please take a look.

**Comment by mattwigway** [comment]
I can't speak to the captureStackTrace error, @trevorgerhardt will have to
weigh in on that one. This error is definitely a backend issue with a
loading cache, we'll have to look in the logs for the stack trace.

**Comment by abyrd** [comment]
Oh right @mattwigway I didn't recognize that as a Guava class name.

**Comment by mattwigway** [comment]
@abyrd was this solved?

**Comment by abyrd** [comment]
Nope @mattwigway I have not been able to reproduce it yet.

**Comment by abyrd** [comment]
@mattwigway The actual cause of the `com.google.common.util.concurrent.ExecutionError` is a MapDB failure in response to a GraphQL query.

```
08:57:38.734 [qtp322187707-20] WARN  org.eclipse.jetty.server.HttpChannel - //localhost:7070/api/graphql?query=%0Aquery%20dataQuery(%24bundleId%3A%20String%2C%20%24route
Ids%3A%20%5BString%5D)%20%7B%0A%20%20bundle%20(bundle_id%3A%20%5B%24bundleId%5D)%20%7B%0A%20%20%20%20feeds%20%7B%0A%20%20%20%20%20%20feed_id%2C%0A%20%20%20%20%20%20check
sum%2C%0A%20%20%20%20%20%20routes%20%7B%0A%20%20%20%20%20%20%20%20route_id%0A%20%20%20%20%20%20%20%20route_short_name%0A%20%20%20%20%20%20%20%20route_long_name%0A%20%20%
20%20%20%20%7D%0A%0A%20%20%20%20%20%20detailRoutes%3A%20routes(route_id%3A%20%24routeIds)%20%7B%0A%20%20%20%20%20%20%20%20route_id%0A%20%20%20%20%20%20%20%20route_short_
name%0A%20%20%20%20%20%20%20%20route_long_name%0A%20%20%20%20%20%20%20%20patterns%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%2C%0A%20%20%20%20%20%20%20%20%20%20pattern_i
d%2C%0A%20%20%20%20%20%20%20%20%20%20geometry%2C%0A%20%20%20%20%20%20%20%20%20%20trips%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20trip_id%2C%0A%20%20%20%20%20%20%20%20%
20%20%20%20trip_short_name%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20trip_headsign%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20start_time%2C%0A%20%20%20%20%20%20%20%20%20%20
%20%20direction_id%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20duration%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20stops%20%7B%0A%20%20%20%20%20
%20%20%20%20%20%20%20stop_id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20stops%20%7B%0A%20%20%20%20%
20%20%20%20stop_id%2C%0A%20%20%20%20%20%20%20%20stop_name%2C%0A%20%20%20%20%20%20%20%20stop_lat%2C%0A%20%20%20%20%20%20%20%20stop_lon%0A%20%20%20%20%20%20%7D%0A%20%20%20
%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%22bundleId%22%3A%22490e7140915948549a5e5b7f9c372a5d%22%2C%22routeIds%22%3A%5B%5D%7D
com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[analyst-master-82c8a2b.jar:1.1]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[analyst-master-82c8a2b.jar:1.1]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[analyst-master-82c8a2b.jar:1.1]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[analyst-master-82c8a2b.jar:1.1]
        at com.conveyal.gtfs.api.ApiMain.getFeedSource(ApiMain.java:109) ~[analyst-master-82c8a2b.jar:1.1]
        at com.conveyal.taui.controllers.GraphQLController.lambda$fetchFeeds$39(GraphQLController.java:148) ~[analyst-master-82c8a2b.jar:1.1]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:1.8.0_101]
```

**Comment by abyrd** [comment]
I wiped out the local cache of GTFS MapDBs on the server, and looking at the log file on the server, I see they were pulled back down from S3, yet this error still happened. Weirdly, the log messages show 18 feeds being pulled from S3, then three are found cached locally, but this bundle contains only 18 feeds. So either corrupted MapDBs are stored on S3, or this is for some reason accessing additional MapDBs in the local disk cache that I don't know about. The short term solution is to re-upload all the files.

Long-term, GTFS-cache needs to use a different database mechanism or switch to a newer MapDB less susceptible to corruption. And we also need to surface more details in the UI when errors like this happen, including stack traces and underlying exceptions (see conveyal/analyst#12).
