### ISSUE TITLE
Cannot upload grid

### ISSUE THREAD

**Issue by abyrd** [conveyal/analysis-ui#285]
When using analysis-ui in analysis mode, I am trying to upload shapefile data to make a grid. I choose a ZIP file containing .shp, .shx and friends. At the moment I select a file, I get the following error:

```
ReactDOMInput.js:156 Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
    at Object.updateWrapper (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3043:2159)
    at ReactDOMComponent.updateComponent (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3022:11383)
    at ReactDOMComponent.receiveComponent (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3022:10750)
    at Object.receiveComponent (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3124:695)
    at ReactCompositeComponentWrapper._updateRenderedComponent (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3016:7758)
    at ReactCompositeComponentWrapper._performComponentUpdate (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3016:7476)
    at ReactCompositeComponentWrapper.updateComponent (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3016:6742)
    at ReactCompositeComponentWrapper.receiveComponent (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3016:5791)
    at Object.receiveComponent (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3124:695)
    at Object.updateChildren (https://scenario-editor-prod.s3.amazonaws.com/assets/index.js:3005:846)
updateWrapper @ ReactDOMInput.js:156
updateComponent @ ReactDOMComponent.js:755
receiveComponent @ ReactDOMComponent.js:710
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
...

**Comment by abyrd** [comment]
@mattwigway points out that the upload may actually be happening despite this error message, but nonetheless the grid does not appear in the UI, with no other errors seen in the server logs or in the Javascript console. Reloading the page (soft or hard) does not make the grid visible in the dropdown list. 

Looking at the network tab of Chrome developer tools, I can see that 1.8MB was transferred in 11 seconds, and the server responded with a 200 to the POST, with the following response body:
```
completedFeatures: -1,
handle: "4e3ca82f-b281-4821-a2fa-7a0b82dd72c7"
status: "PROCESSING"
totalFeatures: -1
```

**Comment by mattwigway** [comment]
Ah, I see what the problem is. We're not currently supporting grids uploaded as zipped shapefiles, as documented at http://docs.analysis.conveyal.com/en/dev/analysis/upload-opportunity-data/ .  We should, created ticket #286, however for the time being this grid seems to upload fine when uploading the unzipped files.

**Comment by abyrd** [comment]
Oh, I'm so used to uploading zipped SHP that I didn't even consider multi-selecting the files. I prefer multi-select to zipping anyway. Thanks.
