### ISSUE TITLE
Bug in analysis

### ISSUE THREAD

**Issue by chourmo** [conveyal/analysis-ui#531]
I found a bug making a normal anaylisis. Following instructions, this is the screenshot and the error message
java.lang.NullPointerException
	at com.conveyal.r5.profile.FastRaptorWorker.doFrequencySearchForRound(FastRaptorWorker.java:460)
	at com.conveyal.r5.profile.FastRaptorWorker.runRaptorForMinute(FastRaptorWorker.java:282)
	at com.conveyal.r5.profile.FastRaptorWorker.route(FastRaptorWorker.java:161)
	at com.conveyal.r5.analyst.TravelTimeComputer.write(TravelTimeComputer.java:171)
	at com.conveyal.r5.analyst.cluster.AnalystWorker.handleOneRequest(AnalystWorker.java:373)
	at com.conveyal.r5.analyst.cluster.AnalystWorker.lambda$null$5(AnalystWorker.java:406)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/7346235/32044803-de0defa6-ba3e-11e7-8950-731bced275ba.png)

**Comment by ansoncfit** [comment]
Is there modification with with Exact Times set to false (i.e. unchecked)?  

https://github.com/conveyal/r5/issues/290 may be the root issue.  Analysis used to fail with exact-times true, now it seems to fail with exact-times false.

**Comment by chourmo** [comment]
Where do I change this setting ?

The bug appears with the default parameters

**Comment by ansoncfit** [comment]
Until the root issue is fixed, "Times are exact" should be selected:

![image](https://user-images.githubusercontent.com/2173529/32382875-c765d6d4-c08c-11e7-97c8-532d16e443a3.png)

**Comment by chourmo** [comment]
Thanks, it seems to work now
