### ISSUE TITLE
Saving region settings consecutively produces errors

### ISSUE THREAD

**Issue by Nate-Wessel** [conveyal/analysis-ui#984]
To reproduce:
1. Open up the region settings page. Make some little change e.g. to the description. 
2. Click save. 
3. Make another little change e.g. chop some digits off a coordinate. 
4. Click save. 

```
Unfortunately it appears an error has occured...

Error on the server

The data you attempted to change is out of date and could not be updated. This project may be open by another user or in another browser tab.

https://staging-api.conveyal.com/api/region/5df14ce26844a22caafc8557
Details

null
com.conveyal.taui.AnalysisServerException
	at com.conveyal.taui.AnalysisServerException.nonce(AnalysisServerException.java:54)
	at com.conveyal.taui.persistence.MongoMap.put(MongoMap.java:241)
	at com.conveyal.taui.persistence.MongoMap.put(MongoMap.java:208)
	at com.conveyal.taui.persistence.MongoMap.updateByUserIfPermitted(MongoMap.java:196)
	at com.conveyal.taui.persistence.MongoMap.updateFromJSONRequest(MongoMap.java:187)
	at com.conveyal.taui.controllers.RegionController.update(RegionController.java:112)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.base/java.lang.Thread.run(Thread.java:834)

Continuing anyways and refreshing your browser may resolve the issue. If not, please take a screenshot of your browser window and email it along with a description of what you were doing to your support team or analysis@conveyal.com.
```

**Comment by Nate-Wessel** [comment]
The GTFS bundles page, which also allows multiple consecutive saves (to bundle/feed names), does not have this problem.
